### ISSUE TITLE
How can I fetch more than one channel? 

### ISSUE THREAD

**Issue by chipimix** [BITalinoWorld/python-serverbit#1]
How can I fetch more than one channel? 

I thought it was like this on the Client side only; but this line doesn't seem to be working:
ws.send("device.start(1000, [0,1,2])");

In the server side the size of the corresponding output message is 1000 instead of the expected 3000.
Thanks in advance!

**Comment by chipimix** [comment]
I also changed the read sample request like so:
ws.send("device.read(1000)[:,-3]")

**Comment by hugoslv** [comment]
Hi there,

ws.send("device.read(1000)[:,-3]") is slicing the matrix returned by read(...) to return only the last column... to receive all the channels you need to change that to ws.send("device.read(1000)"); [0, 1, 2] will be the last 3 columns.

In the meanwhile a more recent and hopefully more user-friendly version of ServerBIT has been made available. Give it a whirl and see if it is more convenient for you:
https://github.com/BITalinoWorld/revolution-python-serverbit/blob/master/README.md

It has a more resilient operation, allowing you configure the acquisition settings, launch ServerBIT and have it working (almost as a service) continuously streaming data and re-establishing the connection when lost. Also, data reaches the JavaScript code as a more manageable JSON object.

Best regards,
Hugo Silva
